### ISSUE TITLE
family details does not show phylogram link or genes associated with family when in multi-gene alignment mode

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#840] opened 2023-07-09 18:25 UTC
e.g.:
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Wm82.gnm2.ann1.Glyma.01G165300,glyma.Wm82.gnm2.ann1.Glyma.02G047000,glyma.Wm82.gnm2.ann1.Glyma.11G077900,glyma.Wm82.gnm2.ann1.Glyma.16G126500
then click on a family in the legend for the microsynteny view. 

<img width="414" alt="image" src="https://github.com/legumeinfo/gcv/assets/2009605/36e1d5d7-5e0a-4bf5-95bf-d46a0d650174">

**Comment by adf-ncgr** [comment] 2023-07-09 19:43
Hmm, does not seem to happen with all multi gene views, e.g. results from 
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Wm82.gnm2.ann1.Glyma.03G172900,glyma.Wm82.gnm2.ann1.Glyma.10G044800,glyma.Wm82.gnm2.ann1.Glyma.13G132500,glyma.Wm82.gnm2.ann1.Glyma.19G173800 seem to behave as expected. 

Now noticing that the earlier example throws an error in the console:
```
main.63283a5153aeee51.js:11 ERROR TypeError: Cannot read properties of undefined (reading 'coordinates')
    at f (806.a1b5737695ca4fdd.js:1:218500)
    at 806.a1b5737695ca4fdd.js:1:219046
    at Array.forEach (<anonymous>)
    at ew (806.a1b5737695ca4fdd.js:1:218774)
    at $h (806.a1b5737695ca4fdd.js:1:219082)
    at 806.a1b5737695ca4fdd.js:1:220420
    at Array.forEach (<anonymous>)
    at Q0 (806.a1b5737695ca4fdd.js:1:219944)
    at sw (806.a1b5737695ca4fdd.js:1:222649)
    at 806.a1b5737695ca4fdd.js:1:294374
```
and fails to display any results tracks. So still a bug, just not exactly what I was thinking when I submitted this. Possible a duplicate issue of something previously reported...

**Comment by adf-ncgr** [comment] 2023-07-09 19:47
Possibly worth noting that if you widen the neighborhood on the problematic example at the given clustering params, the queries are split into separate groups and it looks like the error is associated with only one of them, although the throwing of the error also prevents other groups from getting/displaying their results, probably due to error not getting handled? 
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Wm82.gnm2.ann1.Glyma.01G165300,glyma.Wm82.gnm2.ann1.Glyma.02G047000,glyma.Wm82.gnm2.ann1.Glyma.11G077900,glyma.Wm82.gnm2.ann1.Glyma.16G126500?algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&bmatched=20&bintermediate=10&bmask=10&bchrgenes=1&bchrlength=100000&linkage=average&cthreshold=20&neighbors=20&matched=4&intermediate=5&sources=lis&bregexp=&border=distance&regexp=&order=distance

**Comment by adf-ncgr** [comment] 2023-08-15 22:28
verifying that this seems to more or less be the same bug as reported in https://github.com/legumeinfo/gcv/issues/424 I think I just had not noticed the impact on the family details page when something goes wrong upstream. I am not going to mark it as a duplicate, however since the examples given here may be of some use in tracking down what the problem is.

**Comment by alancleary** [comment] 2023-08-16 20:23
Confirmed this is a duplicate of #424. Closing.

**Closed by alancleary** 2023-08-16 20:23 UTC
Labels: bug
