### ISSUE TITLE
macrosynteny block metrics- make use of them!

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#381] opened 2021-03-10 02:45 UTC
the UI for requesting macrosynteny blocks will need to accomodate requesting metrics, and the metrics could be used for various purposes, e.g.:
- sorting
- filtering
- setting alpha level of block representations

**Comment by alancleary** [comment] 2022-01-11 00:07
I created a new "macro-metrics" branch and pushed a commit (72758ed7440cb81563613646d923eedfafef7826) that adds "Distance" as a choice in the macro-synteny track order menu.

For now the metric being used is hard-code to the Jaccard _distance_ with an 2-gram alphabet where reversals are considered matches, i.e. this is the metric the macro-synteny service is told to compute for each block. The actual "distance" the client uses to order macro-synteny tracks is the average Jaccard _index_ for a track multiplied by the number of reference genes "covered" by the track's blocks.

This is very simple by design since there's a lot of questions that still need to be answered. In no particular order:

- Is this a reasonable way to compute "distance" between blocks and a reference chromosome?
- Do we want to expose other metrics to users? And/or do we want to expose metric parameters to users, i.e. n-gram size, support for reversals, etc?
- If we want to stick with one metric, is Jaccard distance the best? There's a multiset Jaccard I prototyped back when we were discussing that was a great approximation of Levenshtein but with much better run-time performance but it's currently not implemented in the macro-synteny microservice.
- If metrics and/or parameters can be changed by the user, do we want to compute metrics client-side to reduce redundant computation of blocks by the server?
- What do you mean by "setting alpha level of block representations"?
- Micro tracks currently can't be filtered by distance so why should macro tracks be filterable by distance? And does such filtration make sense if users can change the metric and/or parameters, i.e. metric values could differ greatly?
- Or do we want to completely rethink the macro-synteny approach, i.e. it could be much more like micro-synteny where slices of chromosomes are returned and the blocks are computed locally? This way blocks could be inherently connected to metric (like the micro-synteny alignment algorithms).

Perhaps @adf-ncgr and I should just have a conversation about this. I'd like to hear what @svengato has to say as well.

**Comment by alancleary** [comment] 2022-01-11 18:16
Following up on my previous comment; a picture is worth 1000 words, so here's 4000 words worth of screenshots:

phavu.Chr02
![macro2022-01-11T18 03 12 881Z](https://user-images.githubusercontent.com/836063/148998393-52329790-ceaf-402d-8a99-94802775b1b4.png)

glyma.Gm15
![macro2022-01-11T18 04 03 608Z](https://user-images.githubusercontent.com/836063/148998399-75086f78-aaec-45f6-913b-3aefd100d01d.png)

vigun.Vu01
![macro2022-01-11T18 05 01 676Z](https://user-images.githubusercontent.com/836063/148998404-d07c8a16-6389-4bbe-91ce-cff85cffba92.png)

medtr.chr1
![macro2022-01-11T18 05 56 098Z](https://user-images.githubusercontent.com/836063/148998408-a65e15ee-b77f-4d90-b488-81ff5fb4e0b5.png)

**Comment by adf-ncgr** [comment] 2022-01-11 18:27
so eloquent! I would enjoy talking about your questions, but I could imagine getting good feedback from other synteny aficionados, so how about I put an agenda item about it for tomorrow's meeting?

**Comment by svengato** [comment] 2022-01-11 18:31
ZZBrowse defaults to Levenshtein distance, but I can change that to Jaccard distance.

**Comment by cann0010** [comment] 2022-01-11 18:50
Is it possible to change to a genomic distance (relative or absolute position on comparison chromosomes), rather than similarity? I find Levenshtein (or Jaccard) confusing in this context. My eye wants to see a genomic dot plot (physical x physical) rather than physical x similarity.

**Comment by cann0010** [comment] 2022-01-11 19:33
Ah, never mind. I was thinking of the ZZBrowse dot-plot-ish display!

**Comment by adf-ncgr** [comment] 2022-01-11 20:57
@cann0010 thanks for clarifying, I was initially confused by your comment; we have discussed whole-chromosome dotplots for GCV previously though- I would indeed be happy to see such a feature!

**Comment by alancleary** [comment] 2022-01-11 21:20
> so eloquent! I would enjoy talking about your questions, but I could imagine getting good feedback from other synteny aficionados, so how about I put an agenda item about it for tomorrow's meeting?

Yes, let's discuss it at tomorrow's meeting.

**Comment by alancleary** [comment] 2022-02-01 18:56
I'm passing this one off to @ATintern. You'll need to make changes in both the microservices repository and the gcv repository. Make the following changes to your forks on these repositories.

In the microservices repository you'll be specifically working on the [pairwise_macro_synteny_blocks](https://github.com/legumeinfo/microservices/tree/main/pairwise_macro_synteny_blocks) microservice:

- Create a "macro-metrics" branch in the microservices repository
- Update the [jaccard distance metric](https://github.com/legumeinfo/microservices/blob/main/pairwise_macro_synteny_blocks/pairwise_macro_synteny_blocks/metrics.py#L5) to optionally support multisets (code below) with the default value set to `False` ([Wikipedia article on the Jaccard index](https://en.wikipedia.org/wiki/Jaccard_index))

In the gcv repository:

- Checkout the "macro-metrics" branch (this branch already exists and is unrelated to the one you just created in the microservices repo)
- Update the [PairwiseBlocks Angular service](https://github.com/legumeinfo/gcv/blob/72758ed7440cb81563613646d923eedfafef7826/src/app/gene/services/pairwise-blocks.service.ts#L50) to use the optional multiset support you just added to the pairwise_macro_synteny_blocks microservices

Once these changes are made, fire up the microservices and GCV using Docker Compose and test that it's indeed working. When you think they're ready to go, commit the changes to your forks of the repository. Be sure to add a descriptive commit message to your commits (see the repositories' commit histories for examples), and then push the commits to GitHub. Once the commits are on GitHub, make a pull request to add your changes to the actual gcv and microservices repositories.

Multiset Jaccard distance:
```python
from collections import Counter
from itertools import chain


def multiJaccard(a, b, n=1, reversals=False, multiset=False):

  # parse args that may have come from string
  if isinstance(n, str):
    n = int(n)
  if isinstance(reversals, str):
    reversals = bool(reversals)

  # base case
  la, lb = len(a), len(b)
  if n > la or n > lb: return 1

  # convert input to n-gram lists
  def nGram(s): return [tuple(s[i:i+n]) for i in range(len(s)-n+1)]
  na, nb = nGram(a), nGram(b)

  # assign n-grams unique IDs
  ids = {}
  i = 0
  for g in chain(na, nb):
    if g not in ids:
      r = g[::-1]
      if reversals and r in ids:
        ids[g] = ids[r]
      else:
        ids[g] = i
        i += 1

  # convert n-gram lists to id iterators
  def gramID(g): return ids[g]
  aIDs, bIDs = map(gramID, na), map(gramID, nb)

  # generate a count map for each list
  def multiSet(l):
    if not multiset:
      return Counter({e:1 for e in l})
    return Counter(l)
  sa, sb = multiSet(aIDs), multiSet(bIDs)

  # compute the Jaccard index
  intersection = sa & sb
  union = sa | sb
  numerator = sum(intersection.values())
  denominator = sum(union.values())
  if denominator == 0:
    denominator = 1

  # return the distance
  return 1-numerator/denominator
```

**Comment by alancleary** [comment] 2022-03-09 20:36
Done in commit e501268c2f974313a7d8a7fde33e4b8ab6b5b3da. Closing.

**Closed by alancleary** 2022-03-09 20:36 UTC
Labels: enhancement

**Comment by svengato** [comment] 2022-03-09 20:41
You mean "Go forth and macrosyntenize"?

**Comment by alancleary** [comment] 2022-03-09 20:48
> You mean "Go forth and macrosyntenize"?

Actually, no. It's languishing in a PR. It should be merged some time next week, though.
