### ISSUE TITLE
pan-gene/gene family identifers can't contain dashes

### ISSUE THREAD

**Issue by ekcannon** [legumeinfo/gcv#1022] opened 2024-01-18 19:49 UTC
The maize pan-genes have names like pan-zea.v2.pan00001, which breaks the GCV. It was necessary to change them to PanZea.v2.pan00001. While the change is fairly easy, it would be best to use the same names everywhere.

**Comment by adf-ncgr** [comment] 2024-01-19 05:05
Hi @ekcannon I might need a little more info on this; as far as I know there's no reason the identifiers can't contain dashes unless there are some weird searching issues they cause due to the way the redisearch system tokenizes things. Can you give some more detail on what broke when you used dashes?

**Comment by john-portwood** [comment] 2024-01-19 15:10
Hi Andrew,

The pan-zea.v2.pan00001 names in the GFA files were causing the micro synteny cluster to not show any matches when searching a gene model. The below screenshot shows an example of this behavior:
![image](https://github.com/legumeinfo/gcv/assets/751475/06ab48af-7fc2-40b7-9f37-ae79d2d7de09)

When removing the hyphen from the pan gene identifiers in the GFA files, expected behavior was returned as shown in this screenshot:
<img width="1770" alt="image" src="https://github.com/legumeinfo/gcv/assets/751475/d32c0f24-17f5-4457-97d5-9f1ce96e92c7">

Hope this helps, if you have any additional questions let me know.

Thanks!
John

**Comment by adf-ncgr** [comment] 2024-01-19 16:28
Thanks @john-portwood, that at least gives me some better sense for what to look for when I try to reproduce the behavior. Based on the screenshot, it sounds like it shouldn't involve the redisearch matching at all, so I'm now very puzzled. But should be easy to add some dashes in our test data gfa and see what happens there. Thanks again for the extra info!

**Comment by adf-ncgr** [comment] 2024-01-21 17:47
OK, I just tried to reproduce this according to my understanding of what you've described but it seems to be working just fine when there are dashes in the gene family identifiers, as shown in the screenshot below (where I just substituted dashes for underscores in the gfa file for our test datafiles). So, I think it must have been some other issue you guys were having previously. I'm going to close this since it seems that the ids can contain dashes without causing obvious problems, but feel free to reopen it or start a new issue if you can't make things work using the naming scheme you prefer.

<img width="1422" alt="image" src="https://github.com/legumeinfo/gcv/assets/2009605/9247873a-7970-4d4a-a507-81be54fabef3">

**Closed by adf-ncgr** 2024-01-21 17:47 UTC
